// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSzDhQdKeee6vf5OGNKoNTyRbLOZmKO1o',
    appId: '1:681754400720:web:806d5217c49121fd9a0bd5',
    messagingSenderId: '681754400720',
    projectId: 'todotask-986a2',
    authDomain: 'todotask-986a2.firebaseapp.com',
    storageBucket: 'todotask-986a2.appspot.com',
    measurementId: 'G-CSV1WKL30J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUB1opWDSfFsoaExxGejVRUNdI0I9d3fc',
    appId: '1:681754400720:android:96cc6b92b3a6c2739a0bd5',
    messagingSenderId: '681754400720',
    projectId: 'todotask-986a2',
    storageBucket: 'todotask-986a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD66DbGgkWH_HQuc1MQF74Lp0fXfPiClD4',
    appId: '1:681754400720:ios:2a479c7fdde5b6ee9a0bd5',
    messagingSenderId: '681754400720',
    projectId: 'todotask-986a2',
    storageBucket: 'todotask-986a2.appspot.com',
    iosClientId: '681754400720-jar4m5r12c9jv4lb41db969mv7p5osqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.posApplicationMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD66DbGgkWH_HQuc1MQF74Lp0fXfPiClD4',
    appId: '1:681754400720:ios:2a479c7fdde5b6ee9a0bd5',
    messagingSenderId: '681754400720',
    projectId: 'todotask-986a2',
    storageBucket: 'todotask-986a2.appspot.com',
    iosClientId: '681754400720-jar4m5r12c9jv4lb41db969mv7p5osqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.posApplicationMobile',
  );
}
